<?php

$localidades=[];

$localidades["910"]= "9 de Julio";
$localidades["519"]= "Adelia María";
$localidades["901"]= "Arrecifes";
$localidades["930"]= "Azul";
$localidades["933"]= "Bahía Blanca";
$localidades["1218"]= "Bandera";
$localidades["944"]= "Benito Juárez";
$localidades["1210"]= "Bernasconi";
$localidades["541"]= "Berrotarán";
$localidades["946"]= "Bolívar";
$localidades["1219"]= "Campo Gallo";
$localidades["36009"]= "Cañada Rosquin";
$localidades["1226"]= "Cap.Fed./Aeroparque";
$localidades["904"]= "Capitán Sarmiento";		
$localidades["962"]= "Carlos Casares";	
$localidades["405"] ="Carlos Pellegrini";			
$localidades["968"]= "Carlos Tejedor";			
$localidades["1227"]=  "Carmen de Areco";		
$localidades["987"]= "Castelli";						
$localidades["1138"]= "Catamarca";					
$localidades["298"]= "Ceres";										
$localidades["1024"]= "Chascomús";								 
$localidades["1025"]= "Chivilcoy";									 
$localidades["1204"]= "Ciudad del L. Gral. San Martín";
$localidades["1140"]= "Comodoro Rivadavia";		 
$localidades["1236"] ="Concepción del Uruguay";		 
$localidades["1141"]= "Concordia";									 
$localidades["1142"]= "Córdoba";									 
$localidades["991"]= "Coronel Dorrego";						
$localidades["1004"]= "Coronel Pringles";					 
$localidades["1008"]= "Coronel Suárez	";
$localidades["1053"]= "Coronel Vidal";		 
$localidades["461"]= 	"Corral de Bustos";	
$localidades["1143"]= "Corrientes";				
$localidades["1201"]=	"Curuzú Cuatiá";		
$localidades["1026"]=	"Daireaux";				
$localidades["1232"]= "Dean Funes";				 
$localidades["1027"]= "Dolores";					
$localidades["1144"]=	"Esquel";					
$localidades["38431"]="Ezeiza";				
$localidades["1237"]= "Federación";			
$localidades["1238"]= "Federal";							 
$localidades["135"	]= "Firmat";							
$localidades["1147"]= "Formosa";							
$localidades["1211"]=	"General Acha";				 
$localidades["32298"]= "GENERAL ALVEAR";	 
$localidades["1228"]= "General Belgrano";				 
$localidades["561"]= "GENERAL DEHEZA";		
$localidades["1212"]=	"General Pico";				 
$localidades["758"	]="General Villegas";			
$localidades["1202"]= "Goya";							
$localidades["1239"]= "Gualeguay";				 
$localidades["1148"]= "Gualeguaychu";			
$localidades["1043"]= "Guaminí";					
$localidades["1044"]=	"Henderson";				 
$localidades["737"]=	"Hernando";					 
$localidades["137"]= "Hughes";						 
$localidades["1205"]= "Humahuaca";				
$localidades["1149"]=	"Iguazú";						 
$localidades["1203"]="Ing. Guillermo Juárez";
$localidades["243"]= "Ituzaingó";					
$localidades["692"]= "Jesús María";				
$localidades["1215"]= "Joaquín V. Gonzalez";
$localidades["1220"]= "Juan B. Alberdi";		
$localidades["1199"]=	"Juan José Castelli";	 
$localidades["1150"]=	"Jujuy";							 
$localidades["818"]= "Junín";							
$localidades["551"]= "La Carlota";					
$localidades["1243"]=	"La Paz";						 
$localidades["1151"]="La Plata";
$localidades["44325"]= "LA QUIACA";	
$localidades["1152"]= "La Rioja";		
$localidades["444"]= "Laboulaye";		
$localidades["1153"]= "Las Flores";	
$localidades["25"]=	"Las Rosas";	 
$localidades["613"]=	"Las Varillas ";	
$localidades["474"]= "Leones";		
$localidades["802"]= "Lincoln";			
$localidades["1048"]=	"Lobería";			 
$localidades["1229"]="Lobos";			
$localidades["32529"]= "MACIA";					
$localidades["1052"]= "Maipú";				
$localidades["1155"]= "Malargüe";					
$localidades["1156"]= "Maquinchao";			
$localidades["1037"]=	"Mar del Plata";			 
$localidades["473"]=	"Marcos Juárez";		 	
$localidades["143"]= "María Teresa";		
$localidades["1157"]= "Mendoza Aero";		
$localidades["1158"]=	"Monte Caseros";		 	 
$localidades["1058"]="Necochea";	
$localidades["1159"]= "Neuquén";					
$localidades["1244"]= "Nogoyá";						
$localidades["1060"]= "Olavarría";					
$localidades["1160"]= "Oran";							
$localidades["1161"]=	"Paraná";						  
$localidades["1214"]=	"Parera";						  	
$localidades["1162"]= "Paso de los Libres";	
$localidades["1066"]= "Pehuajó";					
$localidades["1068"]=	"Pellegrini";					  	 
$localidades["878"]=" Pergamino";		
$localidades["1164"]= "Pilar (obs. Prov. Cba.)";						
$localidades["1165"]= "Posadas";											
$localidades["1166"]= "Presidente Roque Saenz Peña";	
$localidades["1167"]= "Puerto Deseado";								
$localidades["78"]=	" Rafaela";										 		  
$localidades["1081"]=	"Rauch";										 		  	
$localidades["180"]= "Reconquista";							
$localidades["533"]= "Río Cuarto";									
$localidades["1169"]=	"Río Gallegos";								 	  	 
$localidades["832"]="Rojas";											
$localidades["1231"]= "Roque Perez";							
$localidades["287" ]= "Rosario";	
$localidades["32702"]= "ROSARIO DEL TALA";		
$localidades["146"]= "Rufino";									
$localidades["1099"]=	"Saladillo";							  		  
$localidades["1102"]=	"Salliqueló";							 	  	
$localidades["1170"]= "Salta";									
$localidades["1171"]= "San Antonio Oeste";			
$localidades["38310"]="SAN CARLOS";					  	  	 
$localidades["1172"]="San Carlos de Bariloche";	
$localidades["321"]= "San Cristóbal";									
$localidades["1247"]= "San José de Feliciano";				
$localidades["1174"]= "San Julián";									
$localidades["1175"]= "San Luis";										
$localidades["1221"]=	"San Miguel de Tucumán";			   		  
$localidades["1208"]=	"San Salvador de Jujuy";				 	 	  	
$localidades["226"]= "Santa Fe";										
$localidades["1198"]= "Santa María";								
$localidades["1178"]=	"Santa Rosa";								 	  	  	 
$localidades["591"]="Santa Rosa de Río Primero";		
$localidades["1179"]= "Santiago del Estero";				
$localidades["1223"]= "Sastre";								
$localidades["228"]= "Sauce Viejo";						
$localidades["1112"]= "Tandil";							
$localidades["43836"]=	"TARTAGAL";					 	   		  
$localidades["1116"]=	"Tornquist";						 	 	 	  	
$localidades["1184"]= "Trelew";								
$localidades["1118"]= "Trenque Lauquen";			
$localidades["1121"]=	"Tres Arroyos	";				 	 	  	  	 
$localidades["1185"]="Tucumán";							
$localidades["1186"]= "Ushuaia";													
$localidades["153"]= "Venado Tuerto";									
$localidades["1248"]= "Victoria";												
$localidades["1187"]= "Viedma";											
$localidades["36751"]=	"VILLA CAÑAS";							 	 	   		  
$localidades["1189"]=	"Villa de María del Río Seco";		 		 	 	 	  	
$localidades["1190"]= "Villa Dolores";									
$localidades["1233"]= "Villa María";											
$localidades["1234"]=	"Villa María del Río Seco";			 	 	 	  	  	 
$localidades["188"]="Villa Ocampo	";	
$localidades["1249"]="Villa Paranacito";								
$localidades["1191"]="Villa Reynolds";								
$localidades["1250"]="Villaguay";								
$localidades["1065"]="Villalonga";								



?>

<select name="localidad" class="selectLoc">

	<option value="910">9 de Julio</option>
	<option value="519">Adelia María</option>
	<option value="901">Arrecifes</option>
	<option value="930">Azul</option>
	<option value="933">Bahía Blanca</option>
	<option value="1218">Bandera</option>
	<option value="944">Benito Juárez</option>
	<option value="1210">Bernasconi</option>
	<option value="541">Berrotarán</option>
	<option value="946">Bolívar</option>
	<option value="1219"   >Campo Gallo</option>
	<option value="36009" selected>Cañada Rosquin</option>
	<option value="1226">Cap.Fed./Aeroparque	</option>
	<option value="904">Capitán Sarmiento</option>
	<option value="962">Carlos Casares</option>
	<option value="405">Carlos Pellegrini	</option>
	<option value="968">Carlos Tejedor</option>
	<option value="1227">Carmen de Areco</option>
	<option value="987" >Castelli</option>
	<option value="1138">Catamarca</option>
	<option value="298">Ceres</option>
	<option value="1024">Chascomús</option>
	<option value="1025">Chivilcoy</option>
	<option value="1204">Ciudad del L. Gral. San Martín</option>
	<option value="1140">Comodoro Rivadavia</option>
	<option value="1236">Concepción del Uruguay</option>
	<option value="1141">Concordia</option>
	<option value="1142">Córdoba</option>
	<option value="991">Coronel Dorrego</option>
	<option value="1004">Coronel Pringles</option>	
	<option value="1008">Coronel Suárez</option>
	<option value="1053">Coronel Vidal</option>
	<option value="461">Corral de Bustos</option>
	<option value="1143">Corrientes</option>
	<option value="1201">Curuzú Cuatiá</option>
	<option value="1026">Daireaux	</option>
	<option value="1232">Dean Funes</option>
	<option value="1027">Dolores</option>
	<option value="1144">Esquel</option>
	<option value="38431">Ezeiza</option>	
	<option value="1237">Federación	</option>
	<option value="1238">Federal</option>
	<option value="135">Firmat</option>
	<option value="1147">Formosa	</option>
	<option value="1211">General Acha</option>
	<option value="32298">GENERAL ALVEAR</option>
	<option value="1228">General Belgrano</option>
	<option value="561">GENERAL DEHEZA	</option>
	<option value="1212">General Pico</option>
	<option value="758">General Villegas</option>
	<option value="1202">Goya</option>
	<option value="1239">Gualeguay</option>
	<option value="1148">Gualeguaychu</option>
	<option value="1043">Guaminí</option>
	<option value="1044">Henderson</option>
	<option value="737">Hernando</option>
	<option value="137">Hughes</option>
	<option value="1205">Humahuaca</option>
	<option value="1149">Iguazú	</option>
	<option value="1203">Ing. Guillermo Juárez</option>
	<option value="243">Ituzaingó</option>
	<option value="692">Jesús María</option>
	<option value="1215">Joaquín V. Gonzalez</option>
	<option value="1220">Juan B. Alberdi</option>
	<option value="1199">Juan José Castelli</option>
	<option value="1150">Jujuy</option>
	<option value="818">Junín</option>
	<option value="551">La Carlota</option>
	<option value="1243">La Paz</option>
	<option value="1151">La Plata</option>
	<option value="44325">LA QUIACA</option>
	<option value="1152">La Rioja</option>
	<option value="444">Laboulaye</option>
	<option value="1153">Las Flores</option>
	<option value="25">Las Rosas</option>
	<option value="613">Las Varillas</option>
	<option value="474">Leones</option>
	<option value="802">Lincoln</option>
	<option value="1048">Lobería</option>
	<option value="1229">Lobos</option>
	<option value="32529">MACIA</option>
	<option value="1052">Maipú</option>
	<option value="1155">Malargüe	</option>
	<option value="1156">Maquinchao</option>
	<option value="1037">Mar del Plata</option>
	<option value="473">Marcos Juárez</option>
	<option value="143">María Teresa</option>
	<option value="1157">Mendoza Aero</option>
	<option value="1158">Monte Caseros</option>
	<option value="1058">Necochea</option>
	<option value="1159">Neuquén</option>
	<option value="1244">Nogoyá</option>
	<option value="1060">Olavarría</option>
	<option value="1160">Oran</option>
	<option value="1161">Paraná</option>
	<option value="1214">Parera</option>
	<option value="1162">Paso de los Libres</option>
	<option value="1066">Pehuajó</option>
	<option value="1068">Pellegrini</option>
	<option value="878">Pergamino</option>	
	<option value="1164">Pilar (obs. Prov. Cba.)</option>
	<option value="1165">Posadas</option>
	<option value="1166">Presidente Roque Saenz Peña</option>
	<option value="1167">Puerto Deseado</option>
	<option value="78">Rafaela</option>
	<option value="1081">Rauch</option>
	<option value="180">Reconquista</option>
	<option value="533">Río Cuarto</option>
	<option value="1169">Río Gallegos	</option>
	<option value="832">Rojas</option>
	<option value="1231">Roque Perez</option>
	<option value="287" ng-selected="true">Rosario</option>
	<option value="32702">ROSARIO DEL TALA</option>
	<option value="146">Rufino</option>
	<option value="1099">Saladillo</option>
	<option value="1102">Salliqueló</option>
	<option value="1170">Salta</option>
	<option value="1171">San Antonio Oeste</option>
	<option value="38310">SAN CARLOS</option>
	<option value="321">San Cristóbal</option>
	<option value="1247">San José de Feliciano</option>
	<option value="1174">San Julián</option>
	<option value="1175">San Luis</option>
	<option value="1221">San Miguel de Tucumán</option>
	<option value="1208">San Salvador de Jujuy</option>
	<option value="226">Santa Fe</option>
	<option value="1198">Santa María</option>
	<option value="1178">Santa Rosa</option>
	<option value="591">Santa Rosa de Río Primero</option>
	<option value="1179">Santiago del Estero</option>
	<option value="1223">Sastre	</option>
	<option value="228">Sauce Viejo</option>
	<option value="1112">Tandil</option>
	<option value="43836">TARTAGAL</option>
	<option value="1116">Tornquist</option>
	<option value="1184">Trelew</option>
	<option value="1118">Trenque Lauquen</option>
	<option value="1121">Tres Arroyos</option>
	<option value="1185">Tucumán</option>
	<option value="1186">Ushuaia</option>
	<option value="153">Venado Tuerto</option>
	<option value="1248">Victoria</option>
	<option value="1187">Viedma</option>
	<option value="36751">VILLA CAÑAS</option>
	<option value="1189">Villa de María del Río Seco</option>
	<option value="1190">Villa Dolores</option>
	<option value="1233">Villa María</option>
	<option value="1234">Villa María del Río Seco</option>
	<option value="188">Villa Ocampo</option>
	<option value="1249">Villa Paranacito</option>
	<option value="1191">Villa Reynolds	</option>
	<option value="1250">Villaguay</option>
	<option value="1065">Villalonga</option>
	
	
</select>